{
 "title": "Router-Health-Check",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Input Packet Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "[[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/data-rate",
     "select": [
      [
       { "params": [ "input_packet_rate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "interface_name", "operator": "=", "value": "GigabitEthernet0/0/0/1" }
     ]
    }
   ]
  },
  {
   "title": "Router Uptime",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XR-shellutil-oper:system-time/uptime",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "ncs540l" }
     ]
    }
   ]
  },
  {
   "title": "Device Traffic",
   "type": "graph",
   "gridPos": { "h": 11, "w": 22, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "[[tag_interface_name]] IN",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters",
     "select": [
      [
       { "params": [ "bytes_received" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "[[tag_interface_name]] OUT",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Input Packet Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "[[tag_interface_name]]",
     "groupBy": [
      { "params": [ "interface_name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters",
     "select": [
      [
       { "params": [ "packets_received" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "interface_name", "operator": "=", "value": "GigabitEthernet0/0/0/1" }
     ]
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization",
     "select": [
      [
       { "params": [ "total_cpu_one_minute" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "ncs540l" }
     ]
    }
   ]
  },
  {
   "title": "Interface Summary",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Total Interfaces",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-pfi-im-cmd-oper:interfaces/interface-summary",
     "select": [
      [
       {
        "params": [
         "interface_counts/interface_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Interfaces Up",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-pfi-im-cmd-oper:interfaces/interface-summary",
     "select": [
      [
       {
        "params": [
         "interface_counts/up_interface_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Interfaces Down",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-pfi-im-cmd-oper:interfaces/interface-summary",
     "select": [
      [
       {
        "params": [
         "interface_counts/down_interface_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Shutdown Interfaces",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-pfi-im-cmd-oper:interfaces/interface-summary",
     "select": [
      [
       {
        "params": [
         "interface_counts/admin_down_interface_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mermory Use Percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Memory Use",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-nto-misc-oper:memory-summary/nodes/node/summary",
     "query": "SELECT (last(\"system-ram-memory\") - last(\"free-application-memory\")) * 100 / last(\"system-ram-memory\") FROM \"Cisco-IOS-XR-nto-misc-oper:memory-summary/nodes/node/summary\"  WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "system_ram_memory" ], "type": "field" },
       { "params": [ "-" ], "type": "math" }
      ],
      [
       { "params": [ "free_application_memory" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Memory Use",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (last(\"system-ram-memory\") - last(\"free-application-memory\")) * 100 / last(\"system-ram-memory\") FROM \"Cisco-IOS-XR-nto-misc-shmem-oper:memory-summary/nodes/node/summary\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}